### ISSUE TITLE
the mongodb was not stable

### ISSUE THREAD

**Issue by hchenxa** [IBM/ibm-mongodb-operator#65]
## Issue Summary

I keep my environment running for one day, find the mongodb restart 100+ times,  
```
[root@hchenxa-inf ~]# oc get pods -l release=mongodb
NAME            READY   STATUS    RESTARTS   AGE
icp-mongodb-0   2/2     Running   8          9h
icp-mongodb-1   2/2     Running   172        9h
icp-mongodb-2   2/2     Running   140        9h
```

And check the mongodb events below:

```
time="2020-03-17T21:31:35Z" level=error msg="Can't connect to MongoDB: Cannot connect using uri: mongodb://metrics:icpmetrics@localhost:27017" source="mongodb_exporter.go:94"
  Warning  Unhealthy  6h25m  kubelet, worker1.ocp43-zc.os.fyre.ibm.com  Readiness probe errored: rpc error: code = Unknown desc = command error: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f1dbd57f8df m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f1dbd57f8df
stack: frame={sp:0x7ffed0e32820, fp:0x0} stack=[0x7ffed0633d08,0x7ffed0e32d40)
00007ffed0e32720:  00007ffed0e32770  00007ffed0e32768
00007ffed0e32730:  000055e520e66e3a <runtime.mmap.func1+90>  0000000000000000
00007ffed0e32740:  00007ffed0e32770  000055e520e2ef1e <runtime.(*mTreap).end+78>
00007ffed0e32750:  0000000000000000  000055e500000001
00007ffed0e32760:  0000000000000000  00000001d0e327e0
00007ffed0e32770:  0000000000000120  0000000000000000
00007ffed0e32780:  0000000000000007  0000000000000130
00007ffed0e32790:  000055e500000013  000055e5217fb098
00007ffed0e327a0:  000000000000011f  0000000000000150
00007ffed0e327b0:  ffffffffffffffa8  0000000000000004
00007ffed0e327c0:  0000003400000013  0000000000000000
00007ffed0e327d0:  0000006e0000005b  0000000000000000
00007ffed0e327e0:  000000770000007c  0000000000000000
00007ffed0e327f0:  ffffffffffffffa8  00007f1dbd905c60
00007ffed0e32800:  0000000000000120  0000000000020a00
00007ffed0e32810:  00007f1dbd90a710  000055e5217fb600
00007ffed0e32820: <0000000000000000  00007f1dbd5ce98a
00007ffed0e32830:  00007f1dba334700  00007f1dbdd849eb
00007ffed0e32840:  000055e5217fb620  00007f1dbdb590cf
00007ffed0e32850:  00007f1dba3349d0  00007f1dba334700
00007ffed0e32860:  00007ffed0e32960  00007ffed0e328a0
00007ffed0e32870:  000055e520e5d0d7 <runtime.step+327>  000055e521568bd2
00007ffed0e32880:  00000000001f7e5d  00000000001f7e5d
00007ffed0e32890:  00007ffed0e328c8  000055e520e5d0a3 <runtime.step+275>
00007ffed0e328a0:  fffffffe7fffffff  ffffffffffffffff
00007ffed0e328b0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328c0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328d0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328e0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328f0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e32900:  ffffffffffffffff  ffffffffffffffff
00007ffed0e32910:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7f1dbd57f8df
stack: frame={sp:0x7ffed0e32820, fp:0x0} stack=[0x7ffed0633d08,0x7ffed0e32d40)
00007ffed0e32720:  00007ffed0e32770  00007ffed0e32768
00007ffed0e32730:  000055e520e66e3a <runtime.mmap.func1+90>  0000000000000000
00007ffed0e32740:  00007ffed0e32770  000055e520e2ef1e <runtime.(*mTreap).end+78>
00007ffed0e32750:  0000000000000000  000055e500000001
00007ffed0e32760:  0000000000000000  00000001d0e327e0
00007ffed0e32770:  0000000000000120  0000000000000000
00007ffed0e32780:  0000000000000007  0000000000000130
00007ffed0e32790:  000055e500000013  000055e5217fb098
00007ffed0e327a0:  000000000000011f  0000000000000150
00007ffed0e327b0:  ffffffffffffffa8  0000000000000004
00007ffed0e327c0:  0000003400000013  0000000000000000
00007ffed0e327d0:  0000006e0000005b  0000000000000000
00007ffed0e327e0:  000000770000007c  0000000000000000
00007ffed0e327f0:  ffffffffffffffa8  00007f1dbd905c60
00007ffed0e32800:  0000000000000120  0000000000020a00
00007ffed0e32810:  00007f1dbd90a710  000055e5217fb600
00007ffed0e32820: <0000000000000000  00007f1dbd5ce98a
00007ffed0e32830:  00007f1dba334700  00007f1dbdd849eb
00007ffed0e32840:  000055e5217fb620  00007f1dbdb590cf
00007ffed0e32850:  00007f1dba3349d0  00007f1dba334700
00007ffed0e32860:  00007ffed0e32960  00007ffed0e328a0
00007ffed0e32870:  000055e520e5d0d7 <runtime.step+327>  000055e521568bd2
00007ffed0e32880:  00000000001f7e5d  00000000001f7e5d
00007ffed0e32890:  00007ffed0e328c8  000055e520e5d0a3 <runtime.step+275>
00007ffed0e328a0:  fffffffe7fffffff  ffffffffffffffff
00007ffed0e328b0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328c0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328d0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328e0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e328f0:  ffffffffffffffff  ffffffffffffffff
00007ffed0e32900:  ffffffffffffffff  ffffffffffffffff
00007ffed0e32910:  ffffffffffffffff  ffffffffffffffff

goroutine 1 [running, locked to thread]:
runtime.asmcgocall(0x55e52113f830, 0xc00003c708)
  /usr/lib/golang/src/runtime/asm_amd64.s:640 +0x3f fp=0xc00003c6f0 sp=0xc00003c6e8 pc=0x55e520e6ca6f
runtime.newm1(0xc00006e380)
  /usr/lib/golang/src/runtime/proc.go:1848 +0xa6 fp=0xc00003c730 sp=0xc00003c6f0 pc=0x55e520e45376
runtime.newm(0x55e52150e498, 0x0)
  /usr/lib/golang/src/runtime/proc.go:1832 +0x93 fp=0xc00003c760 sp=0xc00003c730 pc=0x55e520e45213
runtime.startTemplateThread(...)
  /usr/lib/golang/src/runtime/proc.go:1868
runtime.main()
  /usr/lib/golang/src/runtime/proc.go:186 +0x2cb fp=0xc00003c7e0 sp=0xc00003c760 pc=0x55e520e4144b
runtime.goexit()
  /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x55e520e6d331

goroutine 2 [force gc (idle)]:
runtime.gopark(0x55e52150e3f0, 0x55e521784250, 0x1411, 0x1)
  /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00003cfb0 sp=0xc00003cf90 pc=0x55e520e41796
runtime.goparkunlock(...)
  /usr/lib/golang/src/runtime/proc.go:310
runtime.forcegchelper()
  /usr/lib/golang/src/runtime/proc.go:253 +0xbb fp=0xc00003cfe0 sp=0xc00003cfb0 pc=0x55e520e4163b
runtime.goexit()
  /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003cfe8 sp=0xc00003cfe0 pc=0x55e520e6d331
created by runtime.init.6
  /usr/lib/golang/src/runtime/proc.go:242 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x55e52150e3f0, 0x55e521784400, 0x140c, 0x1)
  /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00003d7a8 sp=0xc00003d788 pc=0x55e520e41796
runtime.goparkunlock(...)
  /usr/lib/golang/src/runtime/proc.go:310
runtime.bgsweep(0xc000018070)
  /usr/lib/golang/src/runtime/mgcsweep.go:70 +0xa0 fp=0xc00003d7d8 sp=0xc00003d7a8 pc=0x55e520e34170
runtime.goexit()
  /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003d7e0 sp=0xc00003d7d8 pc=0x55e520e6d331
created by runtime.gcenable
  /usr/lib/golang/src/runtime/mgc.go:210 +0x5e

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x55e52150e3f0, 0x55e521784720, 0x140d, 0x1)
  /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00003df40 sp=0xc00003df20 pc=0x55e520e41796
runtime.goparkunlock(...)
  /usr/lib/golang/src/runtime/proc.go:310
runtime.bgscavenge(0xc000018070)
  /usr/lib/golang/src/runtime/mgcscavenge.go:299 +0xe5 fp=0xc00003dfd8 sp=0xc00003df40 pc=0x55e520e337f5
runtime.goexit()
  /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003dfe0 sp=0xc00003dfd8 pc=0x55e520e6d331
created by runtime.gcenable
  /usr/lib/golang/src/runtime/mgc.go:211 +0x80

rax    0x0
rbx    0x6
rcx    0x7f1dbd57f8df
rdx    0x0
rdi    0x2
rsi    0x7ffed0e32820
rbp    0x55e5211bdd8e
rsp    0x7ffed0e32820
r8     0x0
r9     0x7ffed0e32820
r10    0x8
r11    0x246
r12    0x55e5217fb740
r13    0x0
r14    0x55e5211b0470
r15    0x0
rip    0x7f1dbd57f8df
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x55e520e6f283 m=2 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x55e521784d70, 0x80, 0x7f1dbb335d78, 0x0, 0x7ffe00000000, 0x7f1dbb335d90, 0x3c, 0x0, 0x7f1dbb335d90, 0x55e520e1c630, ...)
  /usr/lib/golang/src/runtime/sys_linux_amd64.s:536 +0x23 fp=0x7f1dbb335d48 sp=0x7f1dbb335d40 pc=0x55e520e6f283
runtime.futexsleep(0x55e521784d70, 0x7f1d00000000, 0xdf8475800)
  /usr/lib/golang/src/runtime/os_linux.go:50 +0xc4 fp=0x7f1dbb335d98 sp=0x7f1dbb335d48 pc=0x55e520e3cfb4
runtime.notetsleep_internal(0x55e521784d70, 0xdf8475800, 0x989680)
  /usr/lib/golang/src/runtime/lock_futex.go:193 +0x130 fp=0x7f1dbb335dd0 sp=0x7f1dbb335d98 pc=0x55e520e1c630
runtime.notetsleep(0x55e521784d70, 0xdf8475800, 0x0)
  /usr/lib/golang/src/runtime/lock_futex.go:216 +0x55 fp=0x7f1dbb335df8 sp=0x7f1dbb335dd0 pc=0x55e520e1c705
runtime.sysmon()
  /usr/lib/golang/src/runtime/proc.go:4316 +0x390 fp=0x7f1dbb335e58 sp=0x7f1dbb335df8 pc=0x55e520e4bde0
runtime.mstart1()
  /usr/lib/golang/src/runtime/proc.go:1201 +0xc7 fp=0x7f1dbb335e80 sp=0x7f1dbb335e58 pc=0x55e520e44177
runtime.mstart()
  /usr/lib/golang/src/runtime/proc.go:1167 +0x70 fp=0x7f1dbb335ea8 sp=0x7f1dbb335e80 pc=0x55e520e44090
rax    0xfffffffffffffffc
rbx    0x0
rcx    0x55e520e6f283
rdx    0x0
rdi    0x55e521784d70
rsi    0x80
rbp    0x, stdout: , stderr: , exit code -1
  Warning  Unhealthy  6h25m  kubelet, worker1.ocp43-zc.os.fyre.ibm.com  Liveness probe failed: time="2020-03-17T21:31:45Z" level=error msg="Could not connect to localhost:27017. Got: EOF" source="connection.go:117"
time="2020-03-17T21:31:45Z" level=error msg="Cannot connect to server using url mongodb://****:****@localhost:27017: no reachable servers" source="connection.go:84"
time="2020-03-17T21:31:45Z" level=error msg="Can't connect to MongoDB: Cannot connect using uri: mongodb://metrics:icpmetrics@localhost:27017" source="mongodb_exporter.go:94"
  Warning  Unhealthy  6h25m  kubelet, worker1.ocp43-zc.os.fyre.ibm.com  Liveness probe failed: MongoDB shell version v4.0.12
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2020-03-17T21:32:00.337+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: short read :
connect@src/mongo/shell/mongo.js:344:17
@(connect):2:6
exception: connect failed
  Warning  Unhealthy  6h4m  kubelet, worker1.ocp43-zc.os.fyre.ibm.com  Readiness probe failed: time="2020-03-17T21:53:19Z" level=error msg="Could not connect to localhost:27017. Got: EOF" source="connection.go:117"
time="2020-03-17T21:53:19Z" level=error msg="Cannot connect to server using url mongodb://****:****@localhost:27017: no reachable servers" source="connection.go:84"
time="2020-03-17T21:53:19Z" level=error msg="Can't connect to MongoDB: Cannot connect using uri: mongodb://metrics:icpmetrics@localhost:27017" source="mongodb_exporter.go:94"
  Warning  Unhealthy  6h3m  kubelet, worker1.ocp43-zc.os.fyre.ibm.com  Liveness probe errored: rpc error: code = Unknown desc = command error: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f3f3849f8df m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f3f3849f8df
stack: frame={sp:0x7ffeefab8830, fp:0x0} stack=[0x7ffeef2b9db8,0x7ffeefab8df0)
00007ffeefab8730:  0000000000210800  0000002200000003
00007ffeefab8740:  00000000ffffffff  00007f3f36257000
00007ffeefab8750:  00007ffeefab8798  00007ffeefab87d0
00007ffeefab8760:  000055b89dd264a3 <runtime.mmap+179>  00007ffeefab87a0
00007ffeefab8770:  0000000000000000  00007ffeefab87c8
00007ffeefab8780:  00007ffeefab87d8  0000000000000040
00007ffeefab8790:  0000000000000040  0000000000000001
00007ffeefab87a0:  000000006e43a318  000055b89e05160c
00007ffeefab87b0:  0000000000210800  000055b89dd811ae <runtime.callCgoMmap+62>
00007ffeefab87c0:  00007ffeefab87c8  00007ffeefab8798
00007ffeefab87d0:  00007ffeefab8820  00007ffeefab8818
00007ffeefab87e0:  000055b89dd78e3a <runtime.mmap.func1+90>  0000000000000000
00007ffeefab87f0:  00007ffeefab8820  000055b89dd40f1e <runtime.(*mTreap).end+78>
00007ffeefab8800:  0000000000000000  000055b800000001
00007ffeefab8810:  0000000000000000  00000001efab8890
00007ffeefab8820:  00007ffeefab88b0  000055b89dd4a8df <runtime.(*mheap).scavengeLocked+559>
00007ffeefab8830: <0000000000000000  00007ffeefab0003
00007ffeefab8840:  000055b800000001  000055b89dd3cba6 <runtime.(*fixalloc).alloc+118>
00007ffeefab8850:  00007f3f38e7b008  0000000000000038
00007ffeefab8860:  0000000000000000  00007ffeefab88f8
00007ffeefab8870:  000055b89dd4a8df <runtime.(*mheap).scavengeLocked+559>  00007f3f38e7b008
00007ffeefab8880:  00007ffeefab88d8  000055b89dd41211 <runtime.(*mTreap).insert+257>
00007ffeefab8890:  00007f3f38e77910  00007f3f00000002
00007ffeefab88a0:  0000000000000000  0000000000000000
00007ffeefab88b0:  fffffffe7fffffff  ffffffffffffffff
00007ffeefab88c0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab88d0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab88e0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab88f0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab8900:  ffffffffffffffff  ffffffffffffffff
00007ffeefab8910:  ffffffffffffffff  ffffffffffffffff
00007ffeefab8920:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7f3f3849f8df
stack: frame={sp:0x7ffeefab8830, fp:0x0} stack=[0x7ffeef2b9db8,0x7ffeefab8df0)
00007ffeefab8730:  0000000000210800  0000002200000003
00007ffeefab8740:  00000000ffffffff  00007f3f36257000
00007ffeefab8750:  00007ffeefab8798  00007ffeefab87d0
00007ffeefab8760:  000055b89dd264a3 <runtime.mmap+179>  00007ffeefab87a0
00007ffeefab8770:  0000000000000000  00007ffeefab87c8
00007ffeefab8780:  00007ffeefab87d8  0000000000000040
00007ffeefab8790:  0000000000000040  0000000000000001
00007ffeefab87a0:  000000006e43a318  000055b89e05160c
00007ffeefab87b0:  0000000000210800  000055b89dd811ae <runtime.callCgoMmap+62>
00007ffeefab87c0:  00007ffeefab87c8  00007ffeefab8798
00007ffeefab87d0:  00007ffeefab8820  00007ffeefab8818
00007ffeefab87e0:  000055b89dd78e3a <runtime.mmap.func1+90>  0000000000000000
00007ffeefab87f0:  00007ffeefab8820  000055b89dd40f1e <runtime.(*mTreap).end+78>
00007ffeefab8800:  0000000000000000  000055b800000001
00007ffeefab8810:  0000000000000000  00000001efab8890
00007ffeefab8820:  00007ffeefab88b0  000055b89dd4a8df <runtime.(*mheap).scavengeLocked+559>
00007ffeefab8830: <0000000000000000  00007ffeefab0003
00007ffeefab8840:  000055b800000001  000055b89dd3cba6 <runtime.(*fixalloc).alloc+118>
00007ffeefab8850:  00007f3f38e7b008  0000000000000038
00007ffeefab8860:  0000000000000000  00007ffeefab88f8
00007ffeefab8870:  000055b89dd4a8df <runtime.(*mheap).scavengeLocked+559>  00007f3f38e7b008
00007ffeefab8880:  00007ffeefab88d8  000055b89dd41211 <runtime.(*mTreap).insert+257>
00007ffeefab8890:  00007f3f38e77910  00007f3f00000002
00007ffeefab88a0:  0000000000000000  0000000000000000
00007ffeefab88b0:  fffffffe7fffffff  ffffffffffffffff
00007ffeefab88c0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab88d0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab88e0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab88f0:  ffffffffffffffff  ffffffffffffffff
00007ffeefab8900:  ffffffffffffffff  ffffffffffffffff
00007ffeefab8910:  ffffffffffffffff  ffffffffffffffff
00007ffeefab8920:  ffffffffffffffff  ffffffffffffffff

goroutine 1 [running]:
runtime.systemstack_switch()
  /usr/lib/golang/src/runtime/asm_amd64.s:330 fp=0xc00003c760 sp=0xc00003c758 pc=0x55b89dd7d230
runtime.main()
  /usr/lib/golang/src/runtime/proc.go:133 +0x67 fp=0xc00003c7e0 sp=0xc00003c760 pc=0x55b89dd531e7
runtime.goexit()
  /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x55b89dd7f331

rax    0x0
rbx    0x6
rcx    0x7f3f3849f8df
rdx    0x0
rdi    0x2
rsi    0x7ffeefab8830
rbp    0x55b89e0cfd8e
rsp    0x7ffeefab8830
r8     0x0
r9     0x7ffeefab8830
r10    0x8
r11    0x246
r12    0x55b89e96a350
r13    0x0
r14    0x55b89e0c2470
r15    0x0
rip    0x7f3f3849f8df
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

will check other environment to see if this was a generic issue.

**Comment by hchenxa** [comment]
@kgcarr

**Comment by kgcarr** [comment]
@hchenxa I need to know more about your env, I have also run into issues running mongoDB here, but it is due to the Persistent Volume used to run mongoDB. For some reason, in Fyre, the persistent volume has more restrictions on it than in other environments, I haven't been able to investigate further than this.

I know if environments like AWS, where we have a dynamic provisioner, this is not a problem

**Comment by grooverdan** [comment]
"pthread_create failed: Resource temporarily unavailable" looks like a memory/thread limit got hit.

**Comment by kgcarr** [comment]
@hchenxa I'm gonna close this, I'm guess it's resolved since we haven't seen this issue in months

Guess it snuck through the cracks since it has no labels, pipeline or assignee for some reason (Probably a github bug)
